print("H=H")                                                                                                                                                                                                                                                
print("H=H")  
print("H=H")  
print("H=H")  
print("H=H")  
print("H=H")  
print("H=H")  
